/**
 * PLOT Design Tokens for React Native
 * Platform-agnostic design system tokens
 * Import these in React Native apps (apps/native)
 * 
 * 🚨 DO NOT EDIT THIS FILE MANUALLY
 * Generated from tokens.config.ts
 * Run: pnpm generate-tokens
 */

export interface ColorPalette {
  // Backgrounds
  bgPrimary: string;
  bgSecondary: string;
  bgElevated: string;

  // Text
  textPrimary: string;
  textSecondary: string;

  // Accent
  accentPrimary: string;
  accentGlow: string;

  // Borders
  borderSubtle: string;
  borderAccent: string;

  // Overlay
  surfaceOverlay: string;

  // Semantic colors
  success: string;
  error: string;
  warning: string;
  info: string;

  // Category colors
  needs: string;
  wants: string;
  repay: string;
  savings: string;
}

export const colors: Record<'light' | 'dark', ColorPalette> = {
  light: {
    // Backgrounds
    bgPrimary: '#F5F0EA',
    bgSecondary: '#FFFFFF',
    bgElevated: '#F0EBE4',

    // Text
    textPrimary: '#111111',
    textSecondary: '#555555',

    // Accent — PLOT green
    accentPrimary: '#0E8345',
    accentGlow: 'rgba(14, 131, 69, 0.15)',

    // Borders
    borderSubtle: 'rgba(0, 0, 0, 0.08)',
    borderAccent: 'rgba(14, 131, 69, 0.3)',

    // Overlay
    surfaceOverlay: 'rgba(0, 0, 0, 0.03)',

    // Semantic colors
    success: '#2E7D32',
    error: '#C92A2A',
    warning: '#FF6B35',
    info: '#1A1A1A',

    // Category colors
    needs: '#8DA399',
    wants: '#C78D75',
    repay: '#EF5350',
    savings: '#6EC97C',
  },

  dark: {
    // Backgrounds
    bgPrimary: '#111111',
    bgSecondary: '#1A1A1A',
    bgElevated: '#222222',

    // Text
    textPrimary: '#F5F0EA',
    textSecondary: '#999999',

    // Accent
    accentPrimary: '#69F0AE',
    accentGlow: 'rgba(105, 240, 174, 0.12)',

    // Borders
    borderSubtle: 'rgba(255, 255, 255, 0.08)',
    borderAccent: 'rgba(105, 240, 174, 0.2)',

    // Overlay
    surfaceOverlay: 'rgba(255, 255, 255, 0.03)',

    // Semantic colors
    success: '#2E7D32',
    error: '#C92A2A',
    warning: '#FF6B35',
    info: '#1A1A1A',

    // Category colors
    needs: '#3D5A6B',
    wants: '#9D6B47',
    repay: '#B8554D',
    savings: '#2E7D5F',
  },
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  '2xl': 48,
  '3xl': 64,
  '4xl': 96,
} as const;

export const borderRadius = {
  sm: 4,
  DEFAULT: 6,
  md: 8,
  lg: 12,
  xl: 16,
  full: 9999,
} as const;

export const typography = {
  fontFamily: {
    display: 'JetBrainsMono',
    heading: 'SpaceMono',
    body: 'Inter',
  },

  fontSize: {
    displayLg: 72,
    displaySm: 40,
    headline: 48,
    headlineSm: 28,
    sub: 24,
    subSm: 18,
    base: 16,
    sm: 14,
    xs: 12,
    label: 14,
    labelSm: 12,
    cta: 16,
    ctaSm: 14,
  },

  lineHeight: {
    tight: 1.05,
    snug: 1.15,
    normal: 1.3,
    relaxed: 1.4,
  },

  letterSpacing: {
    tighter: -0.02,
    tight: -0.01,
    normal: 0,
    wide: 0.01,
    wider: 0.02,
    widest: 0.04,
    ultraWide: 0.06,
    label: 0.15,
    cta: 0.2,
  },

  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
  },
} as const;

export const shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  DEFAULT: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  glow: {
    shadowColor: '#0E8345',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 4,
  },
} as const;

export const zIndex = {
  dropdown: 50,
  sticky: 100,
  modal: 200,
  popover: 300,
  tooltip: 400,
  toast: 500,
} as const;

// Type exports for TypeScript autocomplete
export type ColorScheme = keyof typeof colors;
export type ColorToken = keyof ColorPalette;
export type SpacingToken = keyof typeof spacing;
export type BorderRadiusToken = keyof typeof borderRadius;
export type FontFamily = keyof typeof typography.fontFamily;
export type FontSize = keyof typeof typography.fontSize;