export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          avatar_url: string | null;
          phone_number: string | null;
          household_id: string | null;
          current_paycycle_id: string | null;
          monthly_income: number;
          onboarding_step: number;
          has_completed_onboarding: boolean;
          subscription_tier: 'free' | 'pro';
          subscription_status: 'active' | 'cancelled' | 'past_due' | null;
          polar_customer_id: string | null;
          founding_member_until: string | null;
          trial_cycles_completed: number;
          trial_ended_at: string | null;
          grace_period_start: string | null;
          trial_milestone_email_sent: boolean;
          trial_ending_email_sent: boolean;
          trial_ended_email_sent: boolean;
          grace_period_reminder_sent: boolean;
          founding_member_ending_soon_email_sent: boolean;
          is_admin: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          household_id?: string | null;
          current_paycycle_id?: string | null;
          monthly_income?: number;
          onboarding_step?: number;
          has_completed_onboarding?: boolean;
          subscription_tier?: 'free' | 'pro';
          subscription_status?: 'active' | 'cancelled' | 'past_due' | null;
          polar_customer_id?: string | null;
          founding_member_until?: string | null;
          trial_cycles_completed?: number;
          trial_ended_at?: string | null;
          grace_period_start?: string | null;
          trial_milestone_email_sent?: boolean;
          trial_ending_email_sent?: boolean;
          trial_ended_email_sent?: boolean;
          grace_period_reminder_sent?: boolean;
          founding_member_ending_soon_email_sent?: boolean;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          household_id?: string | null;
          current_paycycle_id?: string | null;
          monthly_income?: number;
          onboarding_step?: number;
          has_completed_onboarding?: boolean;
          subscription_tier?: 'free' | 'pro';
          subscription_status?: 'active' | 'cancelled' | 'past_due' | null;
          polar_customer_id?: string | null;
          founding_member_until?: string | null;
          trial_cycles_completed?: number;
          trial_ended_at?: string | null;
          grace_period_start?: string | null;
          trial_milestone_email_sent?: boolean;
          trial_ending_email_sent?: boolean;
          trial_ended_email_sent?: boolean;
          grace_period_reminder_sent?: boolean;
          founding_member_ending_soon_email_sent?: boolean;
          is_admin?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      households: {
        Row: {
          id: string;
          owner_id: string;
          name: string | null;
          is_couple: boolean;
          partner_name: string | null;
          partner_income: number;
          total_monthly_income: number;
          needs_percent: number;
          wants_percent: number;
          savings_percent: number;
          repay_percent: number;
          pay_day: number | null;
          pay_cycle_type: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          pay_cycle_anchor: string | null;
          joint_ratio: number;
          currency: 'GBP' | 'USD' | 'EUR';
          created_at: string;
          updated_at: string;
          partner_email: string | null;
          partner_auth_token: string | null;
          partner_invite_status: 'none' | 'pending' | 'accepted';
          partner_invite_sent_at: string | null;
          partner_last_login_at: string | null;
          partner_accepted_at: string | null;
          partner_user_id: string | null;
          founding_member_until: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name?: string | null;
          is_couple?: boolean;
          partner_name?: string | null;
          partner_income?: number;
          total_monthly_income?: number;
          needs_percent?: number;
          wants_percent?: number;
          savings_percent?: number;
          repay_percent?: number;
          pay_day?: number | null;
          pay_cycle_type?: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          pay_cycle_anchor?: string | null;
          joint_ratio?: number;
          currency?: 'GBP' | 'USD' | 'EUR';
          created_at?: string;
          updated_at?: string;
          partner_email?: string | null;
          partner_auth_token?: string | null;
          partner_invite_status?: 'none' | 'pending' | 'accepted';
          partner_invite_sent_at?: string | null;
          partner_last_login_at?: string | null;
          partner_accepted_at?: string | null;
          partner_user_id?: string | null;
          founding_member_until?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string | null;
          is_couple?: boolean;
          partner_name?: string | null;
          partner_income?: number;
          total_monthly_income?: number;
          needs_percent?: number;
          wants_percent?: number;
          savings_percent?: number;
          repay_percent?: number;
          pay_day?: number | null;
          pay_cycle_type?: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          pay_cycle_anchor?: string | null;
          joint_ratio?: number;
          currency?: 'GBP' | 'USD' | 'EUR';
          created_at?: string;
          updated_at?: string;
          partner_email?: string | null;
          partner_auth_token?: string | null;
          partner_invite_status?: 'none' | 'pending' | 'accepted';
          partner_invite_sent_at?: string | null;
          partner_last_login_at?: string | null;
          partner_accepted_at?: string | null;
          partner_user_id?: string | null;
          founding_member_until?: string | null;
        };
      };
      income_sources: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          amount: number;
          frequency_rule: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          day_of_month: number | null;
          anchor_date: string | null;
          payment_source: 'me' | 'partner' | 'joint';
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          amount: number;
          frequency_rule?: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          day_of_month?: number | null;
          anchor_date?: string | null;
          payment_source?: 'me' | 'partner' | 'joint';
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          amount?: number;
          frequency_rule?: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          day_of_month?: number | null;
          anchor_date?: string | null;
          payment_source?: 'me' | 'partner' | 'joint';
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      paycycles: {
        Row: {
          id: string;
          household_id: string;
          status: 'active' | 'draft' | 'completed' | 'archived';
          name: string | null;
          start_date: string;
          end_date: string;
          total_income: number;
          snapshot_user_income: number;
          snapshot_partner_income: number;
          total_allocated: number;
          alloc_needs_me: number;
          alloc_needs_partner: number;
          alloc_needs_joint: number;
          alloc_wants_me: number;
          alloc_wants_partner: number;
          alloc_wants_joint: number;
          alloc_savings_me: number;
          alloc_savings_partner: number;
          alloc_savings_joint: number;
          alloc_repay_me: number;
          alloc_repay_partner: number;
          alloc_repay_joint: number;
          rem_needs_me: number;
          rem_needs_partner: number;
          rem_needs_joint: number;
          rem_wants_me: number;
          rem_wants_partner: number;
          rem_wants_joint: number;
          rem_savings_me: number;
          rem_savings_partner: number;
          rem_savings_joint: number;
          rem_repay_me: number;
          rem_repay_partner: number;
          rem_repay_joint: number;
          ritual_closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          status?: 'active' | 'draft' | 'completed' | 'archived';
          name?: string | null;
          start_date: string;
          end_date: string;
          total_income?: number;
          snapshot_user_income?: number;
          snapshot_partner_income?: number;
          total_allocated?: number;
          alloc_needs_me?: number;
          alloc_needs_partner?: number;
          alloc_needs_joint?: number;
          alloc_wants_me?: number;
          alloc_wants_partner?: number;
          alloc_wants_joint?: number;
          alloc_savings_me?: number;
          alloc_savings_partner?: number;
          alloc_savings_joint?: number;
          alloc_repay_me?: number;
          alloc_repay_partner?: number;
          alloc_repay_joint?: number;
          rem_needs_me?: number;
          rem_needs_partner?: number;
          rem_needs_joint?: number;
          rem_wants_me?: number;
          rem_wants_partner?: number;
          rem_wants_joint?: number;
          rem_savings_me?: number;
          rem_savings_partner?: number;
          rem_savings_joint?: number;
          rem_repay_me?: number;
          rem_repay_partner?: number;
          rem_repay_joint?: number;
          ritual_closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          status?: 'active' | 'draft' | 'completed' | 'archived';
          name?: string | null;
          start_date?: string;
          end_date?: string;
          total_income?: number;
          snapshot_user_income?: number;
          snapshot_partner_income?: number;
          total_allocated?: number;
          alloc_needs_me?: number;
          alloc_needs_partner?: number;
          alloc_needs_joint?: number;
          alloc_wants_me?: number;
          alloc_wants_partner?: number;
          alloc_wants_joint?: number;
          alloc_savings_me?: number;
          alloc_savings_partner?: number;
          alloc_savings_joint?: number;
          alloc_repay_me?: number;
          alloc_repay_partner?: number;
          alloc_repay_joint?: number;
          rem_needs_me?: number;
          rem_needs_partner?: number;
          rem_needs_joint?: number;
          rem_wants_me?: number;
          rem_wants_partner?: number;
          rem_wants_joint?: number;
          rem_savings_me?: number;
          rem_savings_partner?: number;
          rem_savings_joint?: number;
          rem_repay_me?: number;
          rem_repay_partner?: number;
          rem_repay_joint?: number;
          ritual_closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      seeds: {
        Row: {
          id: string;
          household_id: string;
          paycycle_id: string;
          name: string;
          amount: number;
          type: 'need' | 'want' | 'savings' | 'repay';
          category: string | null;
          payment_source: 'me' | 'partner' | 'joint';
          is_recurring: boolean;
          is_paid: boolean;
          is_paid_me: boolean;
          is_paid_partner: boolean;
          amount_me: number;
          amount_partner: number;
          split_ratio: number | null;
          uses_joint_account: boolean;
          linked_pot_id: string | null;
          linked_repayment_id: string | null;
          created_by_owner: boolean | null;
          due_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          paycycle_id: string;
          name: string;
          amount: number;
          type: 'need' | 'want' | 'savings' | 'repay';
          category?: string | null;
          payment_source: 'me' | 'partner' | 'joint';
          is_recurring?: boolean;
          is_paid?: boolean;
          is_paid_me?: boolean;
          is_paid_partner?: boolean;
          amount_me?: number;
          amount_partner?: number;
          split_ratio?: number | null;
          uses_joint_account?: boolean;
          linked_pot_id?: string | null;
          linked_repayment_id?: string | null;
          created_by_owner?: boolean;
          due_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          paycycle_id?: string;
          name?: string;
          amount?: number;
          type?: 'need' | 'want' | 'savings' | 'repay';
          category?: string | null;
          payment_source?: 'me' | 'partner' | 'joint';
          is_recurring?: boolean;
          is_paid?: boolean;
          is_paid_me?: boolean;
          is_paid_partner?: boolean;
          amount_me?: number;
          amount_partner?: number;
          split_ratio?: number | null;
          uses_joint_account?: boolean;
          linked_pot_id?: string | null;
          linked_repayment_id?: string | null;
          created_by_owner?: boolean;
          due_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      pots: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          current_amount: number;
          target_amount: number;
          target_date: string | null;
          status: 'active' | 'complete' | 'paused';
          icon: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          current_amount?: number;
          target_amount: number;
          target_date?: string | null;
          status?: 'active' | 'complete' | 'paused';
          icon?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          current_amount?: number;
          target_amount?: number;
          target_date?: string | null;
          status?: 'active' | 'complete' | 'paused';
          icon?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      repayments: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          starting_balance: number;
          current_balance: number;
          interest_rate: number | null;
          target_date: string | null;
          status: 'active' | 'paid' | 'paused';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          starting_balance: number;
          current_balance: number;
          interest_rate?: number | null;
          target_date?: string | null;
          status?: 'active' | 'paid' | 'paused';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          starting_balance?: number;
          current_balance?: number;
          interest_rate?: number | null;
          target_date?: string | null;
          status?: 'active' | 'paid' | 'paused';
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          household_id: string;
          polar_subscription_id: string;
          polar_product_id: string | null;
          status: 'active' | 'cancelled' | 'past_due' | 'trialing';
          current_tier: 'free' | 'pro' | null;
          trial_end_date: string | null;
          metadata: Record<string, string | null> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          polar_subscription_id: string;
          polar_product_id?: string | null;
          status?: 'active' | 'cancelled' | 'past_due' | 'trialing';
          current_tier?: 'free' | 'pro' | null;
          trial_end_date?: string | null;
          metadata?: Record<string, string | null> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          polar_subscription_id?: string;
          polar_product_id?: string | null;
          status?: 'active' | 'cancelled' | 'past_due' | 'trialing';
          current_tier?: 'free' | 'pro' | null;
          trial_end_date?: string | null;
          metadata?: Record<string, string | null> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_events: {
        Row: {
          id: string;
          user_id: string | null;
          event_type: string;
          resource: string | null;
          resource_detail: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          event_type: string;
          resource?: string | null;
          resource_detail?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          event_type?: string;
          resource?: string | null;
          resource_detail?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
      push_tokens: {
        Row: {
          id: string;
          user_id: string;
          token: string;
          platform: 'ios' | 'android';
          payday_reminders: boolean;
          partner_activity: boolean;
          bills_marked_paid: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          token: string;
          platform: 'ios' | 'android';
          payday_reminders?: boolean;
          partner_activity?: boolean;
          bills_marked_paid?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          token?: string;
          platform?: 'ios' | 'android';
          payday_reminders?: boolean;
          partner_activity?: boolean;
          bills_marked_paid?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          household_id: string;
          user_id: string;
          title: string;
          body: string | null;
          source_module: string;
          source_entity_id: string | null;
          action_url: string | null;
          is_read: boolean;
          push_sent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          user_id: string;
          title: string;
          body?: string | null;
          source_module: string;
          source_entity_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          push_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          user_id?: string;
          title?: string;
          body?: string | null;
          source_module?: string;
          source_entity_id?: string | null;
          action_url?: string | null;
          is_read?: boolean;
          push_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      activity_feed: {
        Row: {
          id: string;
          household_id: string;
          actor_user_id: string | null;
          actor_type: 'user' | 'partner' | 'system';
          action: string;
          object_name: string;
          object_detail: string | null;
          source_module: string;
          source_entity_id: string | null;
          action_url: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          actor_user_id?: string | null;
          actor_type: 'user' | 'partner' | 'system';
          action: string;
          object_name: string;
          object_detail?: string | null;
          source_module: string;
          source_entity_id?: string | null;
          action_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          actor_user_id?: string | null;
          actor_type?: 'user' | 'partner' | 'system';
          action?: string;
          object_name?: string;
          object_detail?: string | null;
          source_module?: string;
          source_entity_id?: string | null;
          action_url?: string | null;
          metadata?: Json;
          created_at?: string;
        };
      };
      roadmap_features: {
        Row: {
          id: string;
          title: string;
          description: string;
          module_key: string;
          icon_name: string;
          status: 'now' | 'next' | 'later' | 'shipped';
          display_order: number;
          key_features: string[];
          estimated_timeline: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          module_key: string;
          icon_name: string;
          status: 'now' | 'next' | 'later' | 'shipped';
          display_order?: number;
          key_features?: string[];
          estimated_timeline?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          module_key?: string;
          icon_name?: string;
          status?: 'now' | 'next' | 'later' | 'shipped';
          display_order?: number;
          key_features?: string[];
          estimated_timeline?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      roadmap_votes: {
        Row: {
          id: string;
          feature_id: string;
          household_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          feature_id: string;
          household_id: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          feature_id?: string;
          household_id?: string;
          user_id?: string;
          created_at?: string;
        };
      };
      changelog_entries: {
        Row: {
          id: string;
          version: string;
          released_at: string;
          content: string;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          version: string;
          released_at?: string;
          content?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          version?: string;
          released_at?: string;
          content?: string;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      projects: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          description: string | null;
          status: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          start_date: string | null;
          target_end_date: string | null;
          linked_pot_id: string | null;
          linked_repayment_id: string | null;
          estimated_budget: number | null;
          actual_spend: number;
          cover_image_url: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          description?: string | null;
          status?: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          start_date?: string | null;
          target_end_date?: string | null;
          linked_pot_id?: string | null;
          linked_repayment_id?: string | null;
          estimated_budget?: number | null;
          actual_spend?: number;
          cover_image_url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          description?: string | null;
          status?: 'planning' | 'active' | 'on_hold' | 'completed' | 'cancelled';
          start_date?: string | null;
          target_end_date?: string | null;
          linked_pot_id?: string | null;
          linked_repayment_id?: string | null;
          estimated_budget?: number | null;
          actual_spend?: number;
          cover_image_url?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      project_phases: {
        Row: {
          id: string;
          project_id: string;
          household_id: string;
          name: string;
          description: string | null;
          status: 'pending' | 'active' | 'completed';
          sort_order: number;
          start_date: string | null;
          end_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          household_id: string;
          name: string;
          description?: string | null;
          status?: 'pending' | 'active' | 'completed';
          sort_order?: number;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          household_id?: string;
          name?: string;
          description?: string | null;
          status?: 'pending' | 'active' | 'completed';
          sort_order?: number;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          description: string | null;
          assigned_to: 'me' | 'partner' | 'both' | 'unassigned';
          status: 'backlog' | 'todo' | 'in_progress' | 'done' | 'skipped';
          priority: 'low' | 'medium' | 'high' | 'urgent';
          due_date: string | null;
          completed_at: string | null;
          project_id: string | null;
          phase_id: string | null;
          routine_id: string | null;
          effort_level: 'quick' | 'medium' | 'involved';
          kanban_order: number;
          linked_module: string | null;
          linked_entity_id: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          description?: string | null;
          assigned_to?: 'me' | 'partner' | 'both' | 'unassigned';
          status?: 'backlog' | 'todo' | 'in_progress' | 'done' | 'skipped';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          due_date?: string | null;
          completed_at?: string | null;
          project_id?: string | null;
          phase_id?: string | null;
          routine_id?: string | null;
          effort_level?: 'quick' | 'medium' | 'involved';
          kanban_order?: number;
          linked_module?: string | null;
          linked_entity_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          description?: string | null;
          assigned_to?: 'me' | 'partner' | 'both' | 'unassigned';
          status?: 'backlog' | 'todo' | 'in_progress' | 'done' | 'skipped';
          priority?: 'low' | 'medium' | 'high' | 'urgent';
          due_date?: string | null;
          completed_at?: string | null;
          project_id?: string | null;
          phase_id?: string | null;
          routine_id?: string | null;
          effort_level?: 'quick' | 'medium' | 'involved';
          kanban_order?: number;
          linked_module?: string | null;
          linked_entity_id?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      routines: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          description: string | null;
          frequency: 'daily' | 'weekly' | 'fortnightly' | 'monthly';
          day_of_week: number | null;
          assignment_mode: 'fixed_me' | 'fixed_partner' | 'alternating' | 'unassigned';
          effort_level: 'quick' | 'medium' | 'involved';
          category: string | null;
          is_active: boolean;
          last_generated_for: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          description?: string | null;
          frequency?: 'daily' | 'weekly' | 'fortnightly' | 'monthly';
          day_of_week?: number | null;
          assignment_mode?: 'fixed_me' | 'fixed_partner' | 'alternating' | 'unassigned';
          effort_level?: 'quick' | 'medium' | 'involved';
          category?: string | null;
          is_active?: boolean;
          last_generated_for?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          description?: string | null;
          frequency?: 'daily' | 'weekly' | 'fortnightly' | 'monthly';
          day_of_week?: number | null;
          assignment_mode?: 'fixed_me' | 'fixed_partner' | 'alternating' | 'unassigned';
          effort_level?: 'quick' | 'medium' | 'involved';
          category?: string | null;
          is_active?: boolean;
          last_generated_for?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          household_id: string;
          title: string;
          description: string | null;
          start_at: string;
          end_at: string | null;
          all_day: boolean;
          recurrence_rule: string | null;
          source_module: string | null;
          source_entity_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          title: string;
          description?: string | null;
          start_at: string;
          end_at?: string | null;
          all_day?: boolean;
          recurrence_rule?: string | null;
          source_module?: string | null;
          source_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          title?: string;
          description?: string | null;
          start_at?: string;
          end_at?: string | null;
          all_day?: boolean;
          recurrence_rule?: string | null;
          source_module?: string | null;
          source_entity_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          description: string | null;
          ingredients: Json;
          servings: number;
          source_url: string | null;
          instructions: string | null;
          image_url: string | null;
          prep_mins: number | null;
          cook_mins: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          description?: string | null;
          ingredients?: Json;
          servings?: number;
          source_url?: string | null;
          instructions?: string | null;
          image_url?: string | null;
          prep_mins?: number | null;
          cook_mins?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          description?: string | null;
          ingredients?: Json;
          servings?: number;
          source_url?: string | null;
          instructions?: string | null;
          image_url?: string | null;
          prep_mins?: number | null;
          cook_mins?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      meal_plan_entries: {
        Row: {
          id: string;
          household_id: string;
          recipe_id: string | null;
          free_text: string | null;
          planned_date: string;
          servings: number | null;
          sort_order: number;
          meal_slot: string;
          is_batch_cook: boolean;
          leftovers_from_meal_plan_entry_id: string | null;
          cooked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          recipe_id?: string | null;
          free_text?: string | null;
          planned_date: string;
          servings?: number | null;
          sort_order?: number;
          meal_slot?: string;
          is_batch_cook?: boolean;
          leftovers_from_meal_plan_entry_id?: string | null;
          cooked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          recipe_id?: string | null;
          free_text?: string | null;
          planned_date?: string;
          servings?: number | null;
          sort_order?: number;
          meal_slot?: string;
          is_batch_cook?: boolean;
          leftovers_from_meal_plan_entry_id?: string | null;
          cooked_at?: string | null;
          created_at?: string;
        };
      };
      grocery_items: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          quantity_text: string | null;
          quantity_value: number | null;
          quantity_unit: string | null;
          source_recipe_id: string | null;
          source_meal_plan_entry_id: string | null;
          is_checked: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          quantity_text?: string | null;
          quantity_value?: number | null;
          quantity_unit?: string | null;
          source_recipe_id?: string | null;
          source_meal_plan_entry_id?: string | null;
          is_checked?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          quantity_text?: string | null;
          quantity_value?: number | null;
          quantity_unit?: string | null;
          source_recipe_id?: string | null;
          source_meal_plan_entry_id?: string | null;
          is_checked?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      pantry_items: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          quantity_value: number | null;
          quantity_unit: string | null;
          location: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          quantity_value?: number | null;
          quantity_unit?: string | null;
          location?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          quantity_value?: number | null;
          quantity_unit?: string | null;
          location?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      trips: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          destination: string;
          start_date: string;
          end_date: string;
          status: 'draft' | 'planning' | 'booked' | 'in_progress' | 'completed' | 'cancelled';
          linked_pot_id: string | null;
          linked_project_id: string | null;
          currency: string;
          notes: string | null;
          cover_image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          destination: string;
          start_date: string;
          end_date: string;
          status?: 'draft' | 'planning' | 'booked' | 'in_progress' | 'completed' | 'cancelled';
          linked_pot_id?: string | null;
          linked_project_id?: string | null;
          currency?: string;
          notes?: string | null;
          cover_image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          destination?: string;
          start_date?: string;
          end_date?: string;
          status?: 'draft' | 'planning' | 'booked' | 'in_progress' | 'completed' | 'cancelled';
          linked_pot_id?: string | null;
          linked_project_id?: string | null;
          currency?: string;
          notes?: string | null;
          cover_image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      itinerary_entries: {
        Row: {
          id: string;
          trip_id: string;
          household_id: string;
          date: string;
          title: string;
          description: string | null;
          start_time: string | null;
          end_time: string | null;
          entry_type: 'travel' | 'accommodation' | 'activity' | 'dining' | 'other';
          booking_ref: string | null;
          booking_url: string | null;
          cost_amount: number | null;
          cost_currency: string | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trip_id: string;
          household_id: string;
          date: string;
          title: string;
          description?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          entry_type?: 'travel' | 'accommodation' | 'activity' | 'dining' | 'other';
          booking_ref?: string | null;
          booking_url?: string | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trip_id?: string;
          household_id?: string;
          date?: string;
          title?: string;
          description?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          entry_type?: 'travel' | 'accommodation' | 'activity' | 'dining' | 'other';
          booking_ref?: string | null;
          booking_url?: string | null;
          cost_amount?: number | null;
          cost_currency?: string | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      trip_budget_items: {
        Row: {
          id: string;
          trip_id: string;
          household_id: string;
          category: 'flights' | 'accommodation' | 'car_rental' | 'activities' | 'food' | 'transport' | 'other';
          name: string;
          planned_amount: number;
          actual_amount: number | null;
          currency: string;
          booking_ref: string | null;
          itinerary_entry_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trip_id: string;
          household_id: string;
          category?: 'flights' | 'accommodation' | 'car_rental' | 'activities' | 'food' | 'transport' | 'other';
          name: string;
          planned_amount?: number;
          actual_amount?: number | null;
          currency?: string;
          booking_ref?: string | null;
          itinerary_entry_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trip_id?: string;
          household_id?: string;
          category?: 'flights' | 'accommodation' | 'car_rental' | 'activities' | 'food' | 'transport' | 'other';
          name?: string;
          planned_amount?: number;
          actual_amount?: number | null;
          currency?: string;
          booking_ref?: string | null;
          itinerary_entry_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      packing_items: {
        Row: {
          id: string;
          trip_id: string;
          household_id: string;
          category: string | null;
          name: string;
          is_packed: boolean;
          assignee: 'me' | 'partner' | 'shared';
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          trip_id: string;
          household_id: string;
          category?: string | null;
          name: string;
          is_packed?: boolean;
          assignee?: 'me' | 'partner' | 'shared';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          trip_id?: string;
          household_id?: string;
          category?: string | null;
          name?: string;
          is_packed?: boolean;
          assignee?: 'me' | 'partner' | 'shared';
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Enums: {
      subscription_tier: 'free' | 'pro';
      subscription_status: 'active' | 'cancelled' | 'past_due' | 'trialing';
      pay_cycle_type: 'specific_date' | 'last_working_day' | 'every_4_weeks';
      paycycle_status: 'active' | 'draft' | 'completed' | 'archived';
      seed_type: 'need' | 'want' | 'savings' | 'repay';
      payment_source: 'me' | 'partner' | 'joint';
      pot_status: 'active' | 'complete' | 'paused';
      repayment_status: 'active' | 'paid' | 'paused';
    };
  };
};

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// Convenience type aliases
export type User = Tables<'users'>;
export type Household = Tables<'households'>;
export type IncomeSource = Tables<'income_sources'>;
export type PayCycle = Tables<'paycycles'>;
export type Seed = Tables<'seeds'>;
export type Pot = Tables<'pots'>;
export type Repayment = Tables<'repayments'>;
export type PushToken = Tables<'push_tokens'>;
export type Notification = Tables<'notifications'>;
export type ActivityFeed = Tables<'activity_feed'>;
export type RoadmapFeature = Tables<'roadmap_features'>;
export type RoadmapVote = Tables<'roadmap_votes'>;
export type ChangelogEntry = Tables<'changelog_entries'>;
export type Project = Tables<'projects'>;
export type ProjectPhase = Tables<'project_phases'>;
export type Task = Tables<'tasks'>;
export type Routine = Tables<'routines'>;
export type Event = Tables<'events'>;
export type Recipe = Tables<'recipes'>;
export type MealPlanEntry = Tables<'meal_plan_entries'>;
export type GroceryItem = Tables<'grocery_items'>;
export type PantryItem = Tables<'pantry_items'>;
export type Trip = Tables<'trips'>;
export type ItineraryEntry = Tables<'itinerary_entries'>;
export type TripBudgetItem = Tables<'trip_budget_items'>;
export type PackingItem = Tables<'packing_items'>;
