#!/usr/bin/env tsx
/**
 * Token Generator
 * Generates platform-specific token files from the canonical source (tokens.config.ts)
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import {
  colorTokens,
  spacingTokens,
  borderRadiusTokens,
  typographyTokens,
  shadowTokens,
  zIndexTokens,
  rgbTokens,
} from '../src/tokens.config';

const SRC_DIR = join(__dirname, '../src');

// ============================================================================
// Generate CSS tokens (for web)
// ============================================================================
function generateCssTokens(): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * PLOT Design Tokens');
  lines.push(' * Shared design system for marketing site and app.');
  lines.push(' * Import this file in your app\'s global CSS.');
  lines.push(' * ');
  lines.push(' * 🚨 DO NOT EDIT THIS FILE MANUALLY');
  lines.push(' * Generated from tokens.config.ts');
  lines.push(' * Run: pnpm generate-tokens');
  lines.push(' */');
  lines.push('');
  lines.push('/* Light mode */');
  lines.push(':root {');
  lines.push('  /* Backgrounds */');
  lines.push(`  --plot-bg-primary: ${colorTokens.light.bgPrimary};`);
  lines.push(`  --plot-bg-secondary: ${colorTokens.light.bgSecondary};`);
  lines.push(`  --plot-bg-elevated: ${colorTokens.light.bgElevated};`);
  lines.push('');
  lines.push('  /* Text */');
  lines.push(`  --plot-text-primary: ${colorTokens.light.textPrimary};`);
  lines.push(`  --plot-text-secondary: ${colorTokens.light.textSecondary};`);
  lines.push('');
  lines.push('  /* Accent — PLOT green */');
  lines.push(`  --plot-accent-primary: ${colorTokens.light.accentPrimary};`);
  lines.push(`  --plot-accent-glow: ${colorTokens.light.accentGlow};`);
  lines.push('');
  lines.push('  /* Borders */');
  lines.push(`  --plot-border-subtle: ${colorTokens.light.borderSubtle};`);
  lines.push(`  --plot-border-accent: ${colorTokens.light.borderAccent};`);
  lines.push('');
  lines.push('  /* Overlay */');
  lines.push(`  --plot-surface-overlay: ${colorTokens.light.surfaceOverlay};`);
  lines.push('');
  lines.push('  /* RGB format for Tailwind opacity (space-separated) */');
  lines.push(`  --plot-accent-rgb: ${rgbTokens.light.accentRgb};`);
  lines.push(`  --plot-bg-primary-rgb: ${rgbTokens.light.bgPrimaryRgb};`);
  lines.push(`  --plot-bg-secondary-rgb: ${rgbTokens.light.bgSecondaryRgb};`);
  lines.push(`  --plot-text-primary-rgb: ${rgbTokens.light.textPrimaryRgb};`);
  lines.push(`  --plot-text-secondary-rgb: ${rgbTokens.light.textSecondaryRgb};`);
  lines.push('');
  lines.push('  /* Aliases for marketing site (maps to plot- tokens) */');
  lines.push('  --bg-primary: var(--plot-bg-primary);');
  lines.push('  --bg-secondary: var(--plot-bg-secondary);');
  lines.push('  --bg-elevated: var(--plot-bg-elevated);');
  lines.push('  --text-primary: var(--plot-text-primary);');
  lines.push('  --text-secondary: var(--plot-text-secondary);');
  lines.push('  --accent-primary: var(--plot-accent-primary);');
  lines.push('  --accent-glow: var(--plot-accent-glow);');
  lines.push('  --border-subtle: var(--plot-border-subtle);');
  lines.push('  --border-accent: var(--plot-border-accent);');
  lines.push('  --surface-overlay: var(--plot-surface-overlay);');
  lines.push('}');
  lines.push('');
  lines.push('/* Dark mode */');
  lines.push('.dark {');
  lines.push(`  --plot-bg-primary: ${colorTokens.dark.bgPrimary};`);
  lines.push(`  --plot-bg-secondary: ${colorTokens.dark.bgSecondary};`);
  lines.push(`  --plot-bg-elevated: ${colorTokens.dark.bgElevated};`);
  lines.push(`  --plot-text-primary: ${colorTokens.dark.textPrimary};`);
  lines.push(`  --plot-text-secondary: ${colorTokens.dark.textSecondary};`);
  lines.push(`  --plot-accent-primary: ${colorTokens.dark.accentPrimary};`);
  lines.push(`  --plot-accent-glow: ${colorTokens.dark.accentGlow};`);
  lines.push(`  --plot-border-subtle: ${colorTokens.dark.borderSubtle};`);
  lines.push(`  --plot-border-accent: ${colorTokens.dark.borderAccent};`);
  lines.push(`  --plot-surface-overlay: ${colorTokens.dark.surfaceOverlay};`);
  lines.push(`  --plot-accent-rgb: ${rgbTokens.dark.accentRgb};`);
  lines.push(`  --plot-bg-primary-rgb: ${rgbTokens.dark.bgPrimaryRgb};`);
  lines.push(`  --plot-bg-secondary-rgb: ${rgbTokens.dark.bgSecondaryRgb};`);
  lines.push(`  --plot-text-primary-rgb: ${rgbTokens.dark.textPrimaryRgb};`);
  lines.push(`  --plot-text-secondary-rgb: ${rgbTokens.dark.textSecondaryRgb};`);
  lines.push('}');

  return lines.join('\n');
}

// ============================================================================
// Generate TypeScript tokens (for React Native)
// ============================================================================
function generateTypeScriptTokens(): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * PLOT Design Tokens for React Native');
  lines.push(' * Platform-agnostic design system tokens');
  lines.push(' * Import these in React Native apps (apps/native)');
  lines.push(' * ');
  lines.push(' * 🚨 DO NOT EDIT THIS FILE MANUALLY');
  lines.push(' * Generated from tokens.config.ts');
  lines.push(' * Run: pnpm generate-tokens');
  lines.push(' */');
  lines.push('');
  
  // Color interface
  lines.push('export interface ColorPalette {');
  lines.push('  // Backgrounds');
  lines.push('  bgPrimary: string;');
  lines.push('  bgSecondary: string;');
  lines.push('  bgElevated: string;');
  lines.push('');
  lines.push('  // Text');
  lines.push('  textPrimary: string;');
  lines.push('  textSecondary: string;');
  lines.push('');
  lines.push('  // Accent');
  lines.push('  accentPrimary: string;');
  lines.push('  accentGlow: string;');
  lines.push('');
  lines.push('  // Borders');
  lines.push('  borderSubtle: string;');
  lines.push('  borderAccent: string;');
  lines.push('');
  lines.push('  // Overlay');
  lines.push('  surfaceOverlay: string;');
  lines.push('');
  lines.push('  // Semantic colors');
  lines.push('  success: string;');
  lines.push('  error: string;');
  lines.push('  warning: string;');
  lines.push('  info: string;');
  lines.push('');
  lines.push('  // Category colors');
  lines.push('  needs: string;');
  lines.push('  wants: string;');
  lines.push('  repay: string;');
  lines.push('  savings: string;');
  lines.push('}');
  lines.push('');

  // Colors
  lines.push('export const colors: Record<\'light\' | \'dark\', ColorPalette> = {');
  lines.push('  light: {');
  lines.push('    // Backgrounds');
  lines.push(`    bgPrimary: '${colorTokens.light.bgPrimary}',`);
  lines.push(`    bgSecondary: '${colorTokens.light.bgSecondary}',`);
  lines.push(`    bgElevated: '${colorTokens.light.bgElevated}',`);
  lines.push('');
  lines.push('    // Text');
  lines.push(`    textPrimary: '${colorTokens.light.textPrimary}',`);
  lines.push(`    textSecondary: '${colorTokens.light.textSecondary}',`);
  lines.push('');
  lines.push('    // Accent — PLOT green');
  lines.push(`    accentPrimary: '${colorTokens.light.accentPrimary}',`);
  lines.push(`    accentGlow: '${colorTokens.light.accentGlow}',`);
  lines.push('');
  lines.push('    // Borders');
  lines.push(`    borderSubtle: '${colorTokens.light.borderSubtle}',`);
  lines.push(`    borderAccent: '${colorTokens.light.borderAccent}',`);
  lines.push('');
  lines.push('    // Overlay');
  lines.push(`    surfaceOverlay: '${colorTokens.light.surfaceOverlay}',`);
  lines.push('');
  lines.push('    // Semantic colors');
  lines.push(`    success: '${colorTokens.light.success}',`);
  lines.push(`    error: '${colorTokens.light.error}',`);
  lines.push(`    warning: '${colorTokens.light.warning}',`);
  lines.push(`    info: '${colorTokens.light.info}',`);
  lines.push('');
  lines.push('    // Category colors');
  lines.push(`    needs: '${colorTokens.light.needs}',`);
  lines.push(`    wants: '${colorTokens.light.wants}',`);
  lines.push(`    repay: '${colorTokens.light.repay}',`);
  lines.push(`    savings: '${colorTokens.light.savings}',`);
  lines.push('  },');
  lines.push('');
  lines.push('  dark: {');
  lines.push('    // Backgrounds');
  lines.push(`    bgPrimary: '${colorTokens.dark.bgPrimary}',`);
  lines.push(`    bgSecondary: '${colorTokens.dark.bgSecondary}',`);
  lines.push(`    bgElevated: '${colorTokens.dark.bgElevated}',`);
  lines.push('');
  lines.push('    // Text');
  lines.push(`    textPrimary: '${colorTokens.dark.textPrimary}',`);
  lines.push(`    textSecondary: '${colorTokens.dark.textSecondary}',`);
  lines.push('');
  lines.push('    // Accent');
  lines.push(`    accentPrimary: '${colorTokens.dark.accentPrimary}',`);
  lines.push(`    accentGlow: '${colorTokens.dark.accentGlow}',`);
  lines.push('');
  lines.push('    // Borders');
  lines.push(`    borderSubtle: '${colorTokens.dark.borderSubtle}',`);
  lines.push(`    borderAccent: '${colorTokens.dark.borderAccent}',`);
  lines.push('');
  lines.push('    // Overlay');
  lines.push(`    surfaceOverlay: '${colorTokens.dark.surfaceOverlay}',`);
  lines.push('');
  lines.push('    // Semantic colors');
  lines.push(`    success: '${colorTokens.dark.success}',`);
  lines.push(`    error: '${colorTokens.dark.error}',`);
  lines.push(`    warning: '${colorTokens.dark.warning}',`);
  lines.push(`    info: '${colorTokens.dark.info}',`);
  lines.push('');
  lines.push('    // Category colors');
  lines.push(`    needs: '${colorTokens.dark.needs}',`);
  lines.push(`    wants: '${colorTokens.dark.wants}',`);
  lines.push(`    repay: '${colorTokens.dark.repay}',`);
  lines.push(`    savings: '${colorTokens.dark.savings}',`);
  lines.push('  },');
  lines.push('};');
  lines.push('');

  // Spacing
  lines.push('export const spacing = {');
  Object.entries(spacingTokens).forEach(([key, value]) => {
    lines.push(`  ${key === '2xl' || key === '3xl' || key === '4xl' ? `'${key}'` : key}: ${value},`);
  });
  lines.push('} as const;');
  lines.push('');

  // Border radius
  lines.push('export const borderRadius = {');
  Object.entries(borderRadiusTokens).forEach(([key, value]) => {
    lines.push(`  ${key === 'DEFAULT' ? 'DEFAULT' : key}: ${value},`);
  });
  lines.push('} as const;');
  lines.push('');

  // Typography
  lines.push('export const typography = {');
  lines.push('  fontFamily: {');
  Object.entries(typographyTokens.fontFamily).forEach(([key, value]) => {
    lines.push(`    ${key}: '${value}',`);
  });
  lines.push('  },');
  lines.push('');
  lines.push('  fontSize: {');
  Object.entries(typographyTokens.fontSize).forEach(([key, value]) => {
    lines.push(`    ${key}: ${value},`);
  });
  lines.push('  },');
  lines.push('');
  lines.push('  lineHeight: {');
  Object.entries(typographyTokens.lineHeight).forEach(([key, value]) => {
    lines.push(`    ${key}: ${value},`);
  });
  lines.push('  },');
  lines.push('');
  lines.push('  letterSpacing: {');
  Object.entries(typographyTokens.letterSpacing).forEach(([key, value]) => {
    lines.push(`    ${key}: ${value},`);
  });
  lines.push('  },');
  lines.push('');
  lines.push('  fontWeight: {');
  Object.entries(typographyTokens.fontWeight).forEach(([key, value]) => {
    lines.push(`    ${key}: '${value}' as const,`);
  });
  lines.push('  },');
  lines.push('} as const;');
  lines.push('');

  // Shadows
  lines.push('export const shadows = {');
  Object.entries(shadowTokens).forEach(([key, value]) => {
    lines.push(`  ${key === 'DEFAULT' ? 'DEFAULT' : key}: {`);
    lines.push(`    shadowColor: '${value.shadowColor}',`);
    lines.push(`    shadowOffset: { width: ${value.shadowOffset.width}, height: ${value.shadowOffset.height} },`);
    lines.push(`    shadowOpacity: ${value.shadowOpacity},`);
    lines.push(`    shadowRadius: ${value.shadowRadius},`);
    lines.push(`    elevation: ${value.elevation},`);
    lines.push('  },');
  });
  lines.push('} as const;');
  lines.push('');

  // Z-index
  lines.push('export const zIndex = {');
  Object.entries(zIndexTokens).forEach(([key, value]) => {
    lines.push(`  ${key}: ${value},`);
  });
  lines.push('} as const;');
  lines.push('');

  // Type exports
  lines.push('// Type exports for TypeScript autocomplete');
  lines.push('export type ColorScheme = keyof typeof colors;');
  lines.push('export type ColorToken = keyof ColorPalette;');
  lines.push('export type SpacingToken = keyof typeof spacing;');
  lines.push('export type BorderRadiusToken = keyof typeof borderRadius;');
  lines.push('export type FontFamily = keyof typeof typography.fontFamily;');
  lines.push('export type FontSize = keyof typeof typography.fontSize;');

  return lines.join('\n');
}

// ============================================================================
// Main
// ============================================================================
function main() {
  console.log('🎨 Generating design tokens...\n');

  // Generate CSS
  const cssContent = generateCssTokens();
  const cssPath = join(SRC_DIR, 'tokens.css');
  writeFileSync(cssPath, cssContent, 'utf-8');
  console.log('✅ Generated: tokens.css');

  // Generate TypeScript
  const tsContent = generateTypeScriptTokens();
  const tsPath = join(SRC_DIR, 'native.ts');
  writeFileSync(tsPath, tsContent, 'utf-8');
  console.log('✅ Generated: native.ts');

  console.log('\n✨ Token generation complete!');
  console.log('   Both CSS and TypeScript tokens are now in sync.\n');
}

main();
