export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          display_name: string | null;
          avatar_url: string | null;
          phone_number: string | null;
          household_id: string | null;
          current_paycycle_id: string | null;
          monthly_income: number;
          onboarding_step: number;
          has_completed_onboarding: boolean;
          subscription_tier: 'free' | 'pro';
          subscription_status: 'active' | 'cancelled' | 'past_due' | null;
          polar_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          household_id?: string | null;
          current_paycycle_id?: string | null;
          monthly_income?: number;
          onboarding_step?: number;
          has_completed_onboarding?: boolean;
          subscription_tier?: 'free' | 'pro';
          subscription_status?: 'active' | 'cancelled' | 'past_due' | null;
          polar_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          display_name?: string | null;
          avatar_url?: string | null;
          phone_number?: string | null;
          household_id?: string | null;
          current_paycycle_id?: string | null;
          monthly_income?: number;
          onboarding_step?: number;
          has_completed_onboarding?: boolean;
          subscription_tier?: 'free' | 'pro';
          subscription_status?: 'active' | 'cancelled' | 'past_due' | null;
          polar_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      households: {
        Row: {
          id: string;
          owner_id: string;
          name: string | null;
          is_couple: boolean;
          partner_name: string | null;
          partner_income: number;
          total_monthly_income: number;
          needs_percent: number;
          wants_percent: number;
          savings_percent: number;
          repay_percent: number;
          pay_day: number | null;
          pay_cycle_type: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          pay_cycle_anchor: string | null;
          joint_ratio: number;
          created_at: string;
          updated_at: string;
          partner_email: string | null;
          partner_auth_token: string | null;
          partner_invite_status: 'none' | 'pending' | 'accepted';
          partner_invite_sent_at: string | null;
          partner_last_login_at: string | null;
          partner_accepted_at: string | null;
          partner_user_id: string | null;
        };
        Insert: {
          id?: string;
          owner_id: string;
          name?: string | null;
          is_couple?: boolean;
          partner_name?: string | null;
          partner_income?: number;
          total_monthly_income?: number;
          needs_percent?: number;
          wants_percent?: number;
          savings_percent?: number;
          repay_percent?: number;
          pay_day?: number | null;
          pay_cycle_type?: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          pay_cycle_anchor?: string | null;
          joint_ratio?: number;
          created_at?: string;
          updated_at?: string;
          partner_email?: string | null;
          partner_auth_token?: string | null;
          partner_invite_status?: 'none' | 'pending' | 'accepted';
          partner_invite_sent_at?: string | null;
          partner_last_login_at?: string | null;
          partner_accepted_at?: string | null;
          partner_user_id?: string | null;
        };
        Update: {
          id?: string;
          owner_id?: string;
          name?: string | null;
          is_couple?: boolean;
          partner_name?: string | null;
          partner_income?: number;
          total_monthly_income?: number;
          needs_percent?: number;
          wants_percent?: number;
          savings_percent?: number;
          repay_percent?: number;
          pay_day?: number | null;
          pay_cycle_type?: 'specific_date' | 'last_working_day' | 'every_4_weeks';
          pay_cycle_anchor?: string | null;
          joint_ratio?: number;
          created_at?: string;
          updated_at?: string;
          partner_email?: string | null;
          partner_auth_token?: string | null;
          partner_invite_status?: 'none' | 'pending' | 'accepted';
          partner_invite_sent_at?: string | null;
          partner_last_login_at?: string | null;
          partner_accepted_at?: string | null;
          partner_user_id?: string | null;
        };
      };
      paycycles: {
        Row: {
          id: string;
          household_id: string;
          status: 'active' | 'draft' | 'completed' | 'archived';
          name: string | null;
          start_date: string;
          end_date: string;
          total_income: number;
          snapshot_user_income: number;
          snapshot_partner_income: number;
          total_allocated: number;
          alloc_needs_me: number;
          alloc_needs_partner: number;
          alloc_needs_joint: number;
          alloc_wants_me: number;
          alloc_wants_partner: number;
          alloc_wants_joint: number;
          alloc_savings_me: number;
          alloc_savings_partner: number;
          alloc_savings_joint: number;
          alloc_repay_me: number;
          alloc_repay_partner: number;
          alloc_repay_joint: number;
          rem_needs_me: number;
          rem_needs_partner: number;
          rem_needs_joint: number;
          rem_wants_me: number;
          rem_wants_partner: number;
          rem_wants_joint: number;
          rem_savings_me: number;
          rem_savings_partner: number;
          rem_savings_joint: number;
          rem_repay_me: number;
          rem_repay_partner: number;
          rem_repay_joint: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          status?: 'active' | 'draft' | 'completed' | 'archived';
          name?: string | null;
          start_date: string;
          end_date: string;
          total_income?: number;
          snapshot_user_income?: number;
          snapshot_partner_income?: number;
          total_allocated?: number;
          alloc_needs_me?: number;
          alloc_needs_partner?: number;
          alloc_needs_joint?: number;
          alloc_wants_me?: number;
          alloc_wants_partner?: number;
          alloc_wants_joint?: number;
          alloc_savings_me?: number;
          alloc_savings_partner?: number;
          alloc_savings_joint?: number;
          alloc_repay_me?: number;
          alloc_repay_partner?: number;
          alloc_repay_joint?: number;
          rem_needs_me?: number;
          rem_needs_partner?: number;
          rem_needs_joint?: number;
          rem_wants_me?: number;
          rem_wants_partner?: number;
          rem_wants_joint?: number;
          rem_savings_me?: number;
          rem_savings_partner?: number;
          rem_savings_joint?: number;
          rem_repay_me?: number;
          rem_repay_partner?: number;
          rem_repay_joint?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          status?: 'active' | 'draft' | 'completed' | 'archived';
          name?: string | null;
          start_date?: string;
          end_date?: string;
          total_income?: number;
          snapshot_user_income?: number;
          snapshot_partner_income?: number;
          total_allocated?: number;
          alloc_needs_me?: number;
          alloc_needs_partner?: number;
          alloc_needs_joint?: number;
          alloc_wants_me?: number;
          alloc_wants_partner?: number;
          alloc_wants_joint?: number;
          alloc_savings_me?: number;
          alloc_savings_partner?: number;
          alloc_savings_joint?: number;
          alloc_repay_me?: number;
          alloc_repay_partner?: number;
          alloc_repay_joint?: number;
          rem_needs_me?: number;
          rem_needs_partner?: number;
          rem_needs_joint?: number;
          rem_wants_me?: number;
          rem_wants_partner?: number;
          rem_wants_joint?: number;
          rem_savings_me?: number;
          rem_savings_partner?: number;
          rem_savings_joint?: number;
          rem_repay_me?: number;
          rem_repay_partner?: number;
          rem_repay_joint?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      seeds: {
        Row: {
          id: string;
          household_id: string;
          paycycle_id: string;
          name: string;
          amount: number;
          type: 'need' | 'want' | 'savings' | 'repay';
          category: string | null;
          payment_source: 'me' | 'partner' | 'joint';
          is_recurring: boolean;
          is_paid: boolean;
          is_paid_me: boolean;
          is_paid_partner: boolean;
          amount_me: number;
          amount_partner: number;
          split_ratio: number | null;
          uses_joint_account: boolean;
          linked_pot_id: string | null;
          linked_repayment_id: string | null;
          created_by_owner: boolean | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          paycycle_id: string;
          name: string;
          amount: number;
          type: 'need' | 'want' | 'savings' | 'repay';
          category?: string | null;
          payment_source: 'me' | 'partner' | 'joint';
          is_recurring?: boolean;
          is_paid?: boolean;
          is_paid_me?: boolean;
          is_paid_partner?: boolean;
          amount_me?: number;
          amount_partner?: number;
          split_ratio?: number | null;
          uses_joint_account?: boolean;
          linked_pot_id?: string | null;
          linked_repayment_id?: string | null;
          created_by_owner?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          paycycle_id?: string;
          name?: string;
          amount?: number;
          type?: 'need' | 'want' | 'savings' | 'repay';
          category?: string | null;
          payment_source?: 'me' | 'partner' | 'joint';
          is_recurring?: boolean;
          is_paid?: boolean;
          is_paid_me?: boolean;
          is_paid_partner?: boolean;
          amount_me?: number;
          amount_partner?: number;
          split_ratio?: number | null;
          uses_joint_account?: boolean;
          linked_pot_id?: string | null;
          linked_repayment_id?: string | null;
          created_by_owner?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      pots: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          current_amount: number;
          target_amount: number;
          target_date: string | null;
          status: 'active' | 'complete' | 'paused';
          icon: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          current_amount?: number;
          target_amount: number;
          target_date?: string | null;
          status?: 'active' | 'complete' | 'paused';
          icon?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          current_amount?: number;
          target_amount?: number;
          target_date?: string | null;
          status?: 'active' | 'complete' | 'paused';
          icon?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      repayments: {
        Row: {
          id: string;
          household_id: string;
          name: string;
          starting_balance: number;
          current_balance: number;
          interest_rate: number | null;
          target_date: string | null;
          status: 'active' | 'paid' | 'paused';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          name: string;
          starting_balance: number;
          current_balance: number;
          interest_rate?: number | null;
          target_date?: string | null;
          status?: 'active' | 'paid' | 'paused';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          name?: string;
          starting_balance?: number;
          current_balance?: number;
          interest_rate?: number | null;
          target_date?: string | null;
          status?: 'active' | 'paid' | 'paused';
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Enums: {
      subscription_tier: 'free' | 'pro';
      subscription_status: 'active' | 'cancelled' | 'past_due';
      pay_cycle_type: 'specific_date' | 'last_working_day' | 'every_4_weeks';
      paycycle_status: 'active' | 'draft' | 'completed' | 'archived';
      seed_type: 'need' | 'want' | 'savings' | 'repay';
      payment_source: 'me' | 'partner' | 'joint';
      pot_status: 'active' | 'complete' | 'paused';
      repayment_status: 'active' | 'paid' | 'paused';
    };
  };
};

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// Convenience type aliases
export type User = Tables<'users'>;
export type Household = Tables<'households'>;
export type PayCycle = Tables<'paycycles'>;
export type Seed = Tables<'seeds'>;
export type Pot = Tables<'pots'>;
export type Repayment = Tables<'repayments'>;
